import type { Metadata } from "next";
import { LandingScene } from "@/components/landing-scene";
import "./pixel.css";

/**
 * The landing page is the only public, indexable surface. Metadata is written
 * for a hungry customer in Kabankalan, not for a developer: the title and
 * description are what appears when the link is shared on Messenger or
 * Facebook, which is where most of the first testers will meet it.
 *
 * The Open Graph image is generated by app/opengraph-image.tsx and picked up
 * automatically; metadataBase lets it resolve to an absolute URL.
 */
const title = "KFD — Food delivery sa Kabankalan City";
const description =
  "Order from local Kabankalan kitchens, pay cash on delivery, and follow your rider until the food reaches your door. Pili, bayad, hintay.";

export const metadata: Metadata = {
  title,
  description,
  applicationName: "KFD",
  alternates: { canonical: "/" },
  openGraph: {
    type: "website",
    url: "/",
    siteName: "KFD — Kabankalan Food Delivery",
    title,
    description,
    locale: "en_PH",
  },
  twitter: {
    card: "summary_large_image",
    title,
    description,
  },
};

export default function HomePage() {
  return <LandingScene />;
}
